import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';
import { fonts } from '../theme/typography';

export const adminStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.white },
  safe: { flex: 1 },
  content: { paddingHorizontal: 24, paddingTop: 20, paddingBottom: 40 },
  kicker: {
    fontFamily: fonts.medium,
    fontSize: 13,
    color: colors.label,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  title: {
    fontFamily: fonts.semiBold,
    fontSize: 32,
    letterSpacing: -0.7,
    color: colors.ink,
    marginTop: 8,
  },
  subtitle: {
    fontFamily: fonts.regular,
    fontSize: 16,
    lineHeight: 24,
    color: colors.muted,
    marginTop: 8,
  },
  stats: { flexDirection: 'row', gap: 10, marginTop: 24 },
  stat: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 14,
    backgroundColor: colors.white,
  },
  statValue: { fontFamily: fonts.semiBold, fontSize: 22, color: colors.ink },
  statLabel: { fontFamily: fonts.regular, fontSize: 12, color: colors.muted, marginTop: 4 },
  section: {
    fontFamily: fonts.semiBold,
    fontSize: 18,
    color: colors.ink,
    marginTop: 28,
    marginBottom: 12,
  },
  empty: { fontFamily: fonts.regular, fontSize: 15, color: colors.muted },
  card: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 16,
    marginBottom: 10,
    backgroundColor: colors.white,
  },
  cardTitle: { fontFamily: fonts.semiBold, fontSize: 16, color: colors.ink },
  cardMeta: { fontFamily: fonts.regular, fontSize: 13, color: colors.muted, marginTop: 4 },
  note: { fontFamily: fonts.regular, fontSize: 13, color: colors.label, marginTop: 8 },
  badge: {
    fontFamily: fonts.medium,
    fontSize: 12,
    color: colors.ink,
    marginBottom: 8,
  },
  row: { flexDirection: 'row', gap: 8, marginTop: 14, flexWrap: 'wrap' },
  primary: {
    flex: 1,
    minWidth: 110,
    height: 46,
    borderRadius: 999,
    backgroundColor: colors.black,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  primaryText: { fontFamily: fonts.medium, fontSize: 14, color: colors.white },
  secondary: {
    flex: 1,
    minWidth: 110,
    height: 46,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  secondaryText: { fontFamily: fonts.medium, fontSize: 14, color: colors.ink },
  pressed: { opacity: 0.88 },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  toggleCopy: { flex: 1, gap: 4 },
  toggleLabel: { fontFamily: fonts.semiBold, fontSize: 15, color: colors.ink },
  toggleHelper: { fontFamily: fonts.regular, fontSize: 13, lineHeight: 18, color: colors.muted },
  pill: {
    minWidth: 54,
    height: 32,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    backgroundColor: colors.white,
  },
  pillOn: {
    backgroundColor: colors.black,
    borderColor: colors.black,
  },
  pillText: { fontFamily: fonts.medium, fontSize: 12, color: colors.ink },
  pillTextOn: { color: colors.white },
  permission: {
    fontFamily: fonts.regular,
    fontSize: 15,
    lineHeight: 24,
    color: colors.ink,
    marginTop: 8,
  },
  staffBadge: {
    marginTop: 16,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: colors.white,
  },
  staffBadgeText: { fontFamily: fonts.medium, fontSize: 13, color: colors.ink },
  signOut: {
    height: 54,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 28,
    backgroundColor: colors.white,
  },
});
