import { describe, expect, it } from 'vitest';
import { generateResume, parseVoiceResume, parseVoiceToJob } from './voice';

describe('parseVoiceToJob', () => {
  it('maps nurse and Gachibowli from a spoken post', () => {
    expect(parseVoiceToJob('Need a nurse in Gachibowli 30k')).toMatchObject({
      title: 'Staff Nurse',
      location: 'Gachibowli',
    });
  });

  it('falls back to Hyderabad for unknown areas', () => {
    expect(parseVoiceToJob('Looking for a cook').location).toBe('Hyderabad');
  });
});

describe('parseVoiceResume', () => {
  it('extracts name, last job, area, and join time', () => {
    expect(parseVoiceResume('I am Priya nurse from Gachibowli I can join immediate')).toEqual({
      name: 'Priya',
      lastJob: 'nurse',
      area: 'Gachibowli',
      joinWhen: 'Immediate',
    });
  });
});

describe('generateResume', () => {
  it('builds a 6-field Orbit resume', () => {
    const text = generateResume({
      name: 'Priya Rao',
      phone: '9876543210',
      area: 'Gachibowli',
      lastJob: 'Staff Nurse',
      joinWhen: 'Immediate',
    });
    expect(text).toContain('Priya Rao');
    expect(text).toContain('Gachibowli');
    expect(text).toContain('Staff Nurse');
    expect(text).toContain('987****210');
    expect(text).not.toContain('9876543210');
    expect(text).toContain('Simple resume generated by Orbit');
  });
});
