import { maskCustomerPhone, redactPhonesInText } from './customerSecurity';

export function parseVoiceToJob(transcript: string): { title: string; location: string; salary: string } {
  const text = transcript.toLowerCase();
  const title = /nurse|నర్స్/.test(text)
    ? 'Staff Nurse'
    : /driver|డ్రైవర్/.test(text)
      ? 'Driver'
      : /account|అకౌంట/.test(text)
        ? 'Accountant'
        : transcript.trim().slice(0, 48) || 'General opening';
  const location = /gachibowli|గచ్చిబౌలి/.test(text)
    ? 'Gachibowli'
    : /hitec|హైటెక్/.test(text)
      ? 'HITEC City'
      : /madhapur|మాధాపూర్/.test(text)
        ? 'Madhapur'
        : 'Hyderabad';
  const salary = /(\d+)\s*(k|thousand|వేల)/i.exec(transcript)?.[0] ?? 'As per interview';
  return { title, location, salary };
}

export function parseVoiceResume(transcript: string): {
  name: string;
  lastJob: string;
  area: string;
  joinWhen: string;
} {
  const nameMatch = /(?:i am|నేను)\s+([a-zA-Z\u0C00-\u0C7F]+)/i.exec(transcript);
  return {
    name: nameMatch?.[1] ?? 'Candidate',
    lastJob: /nurse|driver|sales|cook|accountant/i.exec(transcript)?.[0] ?? 'Previous local role',
    area: /gachibowli|hitec|madhapur|uppal|kompally/i.exec(transcript)?.[0] ?? 'Hyderabad',
    joinWhen: /immediate|today|tomorrow|ఇప్పుడే/i.test(transcript) ? 'Immediate' : 'In 7 days',
  };
}

export function generateResume(input: {
  name: string;
  phone: string;
  area: string;
  lastJob: string;
  joinWhen: string;
  voiceNote?: string;
  education?: string;
  skills?: string;
}): string {
  return [
    `${input.name}`,
    `Area: ${input.area} · Hyderabad`,
    input.phone.trim() ? `Phone (via Orbit): ${maskCustomerPhone(input.phone)}` : '',
    `Recent work: ${input.lastJob}`,
    input.education?.trim() ? `Education: ${input.education.trim()}` : '',
    input.skills?.trim() ? `Skills: ${input.skills.trim()}` : '',
    `Can join: ${input.joinWhen}`,
    input.voiceNote ? `Voice note: ${redactPhonesInText(input.voiceNote)}` : '',
    '',
    'Simple resume generated by Orbit. No PDF uploaded.',
  ]
    .filter(Boolean)
    .join('\n');
}
